version: '3.8'

services:
  mongodb: 
    image: mongo:latest
    environment:
      - MONGODB_DATABASE="catalog-manager"
    ports:
      - 27017:27017

#   postgres:
#     image: postgres:latest
#     environment:
#       - POSTGRES_USER=postgres   # Replace with your desired username
#       - POSTGRES_PASSWORD=root  # Replace with your desired password
#       - POSTGRES_DB=catalog-manager    # Replace with your desired database name
#     ports:
#       - 5433:5432  # Maps PostgreSQL port to host
#     volumes:
#       - postgres-data:/var/lib/postgresql/data  # Persists data across container restarts

# volumes:
#   mongo-data:
#   postgres-data: